# Generated by Django 3.2 on 2022-05-18 12:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220516_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skill_set',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website_url',
        ),
        migrations.AddField(
            model_name='user',
            name='recommended',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField(blank=True)),
                ('company', models.CharField(blank=True, max_length=20)),
                ('company_email', models.EmailField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^010-?[\\d]{4}-?[\\d]{4}$')])),
                ('avatar', models.ImageField(blank=True, help_text='48px * 48px 크기의 png/jpg를 넣어주세요. ', upload_to='accounts/avatar/%Y/%m/%d')),
                ('available', models.TextField(blank=True)),
                ('skill_set', models.ManyToManyField(blank=True, to='accounts.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
