# Generated by Django 3.2 on 2022-06-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220609_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Settings에서 정보를 입력해주세요'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(default='Settings에서 정보를 입력해주세요', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_email',
            field=models.EmailField(default='Settings에서 정보를 입력해주세요', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill_set',
            field=models.CharField(default='Settings에서 정보를 입력해주세요', max_length=20),
        ),
    ]
