# Generated by Django 3.2 on 2022-05-18 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='all', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('attached_file', models.FileField(blank=True, upload_to='')),
                ('cover_img', models.ImageField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL)),
                ('post_likes', models.ManyToManyField(default=0, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
                ('post_tag_set', models.ManyToManyField(blank=True, to='shareinfo.Tag')),
            ],
        ),
    ]
