# Generated by Django 3.2 on 2022-05-29 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shareinfo', '0003_post_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attached_file',
            field=models.FileField(blank=True, upload_to='shareinfo/post/cover/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_img',
            field=models.ImageField(blank=True, upload_to='shareinfo/post/cover/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareinfo.post')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
