# Generated by Django 3.2 on 2022-05-31 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareinfo', '0004_auto_20220529_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
    ]
