# Generated by Django 3.2 on 2022-05-31 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareinfo', '0006_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_likes',
            new_name='like_user_set',
        ),
    ]
