# Generated by Django 3.2 on 2022-06-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareinfo', '0010_auto_20220605_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_ip',
            field=models.GenericIPAddressField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='shareinfo/post/cover/%Y/%m/%d', verbose_name='Attached File'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='shareinfo/post/cover/%Y/%m/%d', verbose_name='Cover Image'),
        ),
    ]
