# Generated by Django 3.2 on 2022-06-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareinfo', '0011_auto_20220606_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='shareinfo/post/file/%Y/%m/%d', verbose_name='Attached File'),
        ),
    ]
